# External parameters
#   CHANNEL
#   PY_VER

steps:
  - checkout: self
    path: ./cctbx

  - checkout: cctbx_project
    path: ./cctbx_project

  # add conda to path
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-16-04#add-conda-to-your-system-path
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  # https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=macos
  - bash: sudo chown -R $USER $CONDA
    displayName: Take ownership of conda installation

  - script: |
      set -xe
      conda create -n test -c ${{ parameters.CHANNEL }} -c conda-forge -y cctbx-base python=$(PY_VER) pytest junit-xml
    displayName: Construct latest conda environment

  # copy extra test files
  - script: |
      set -xe
      source activate test
      cd $(Pipeline.Workspace)
      cp -a cctbx_project/ucif/antlr3 ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/ucif
      cp cctbx_project/ucif/*.cpp ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/ucif
      cp cctbx_project/ucif/examples/*.cpp ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/ucif/examples
      cp -a cctbx_project/fable/test/lenient ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/fable/test
      cp -a cctbx_project/fable/test/semantic_error ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/fable/test
      cp -a cctbx_project/fable/test/syntax_error ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/fable/test
      cp -a cctbx_project/fable/test/unsupported ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/fable/test
      cp -a cctbx_project/fable/test/valid ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages/fable/test
    displayName: Copy additional test files for fable and iotbx tests

  - script: |
      set -xe
      source activate test
      cd $(Pipeline.Workspace)
      python cctbx/.azure-pipelines/scripts/download-phenix-regression.py --organization cctbx --project cctbx_project
      unzip phenix_regression.zip
      mv phenix_regression ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages
      ls ${CONDA_PREFIX}/lib/python$(PY_VER)/site-packages
    displayName: Copy phenix_regression artifact

  # module=cbflib_adaptbx
  - script: |
      set -xe
      source activate test
      cd $(Pipeline.Workspace)
      mkdir tests
      cd tests
      export PYTHONDEVMODE=1
      export PYTHONTRACEMALLOC=1
      libtbx.run_tests_parallel \
        module=annlib_adaptbx \
        module=boost_adaptbx \
        module=cctbx \
        module=cctbx_website \
        module=cma_es \
        module=fable \
        module=gltbx \
        module=iotbx \
        module=libtbx \
        module=rstbx \
        module=scitbx \
        module=smtbx \
        module=spotfinder \
        nproc=4
    failOnStderr: false
    displayName: Run subset of tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Pipeline.Workspace)/tests/output.xml'
