# Update nightly-feedstock to trigger building of conda packages

resources:
  pipelines:
  - pipeline: source_tarball
    source: source_tarball
    trigger:
      branches:
        include:
        - ci
        - master
        - releases/*
  repositories:
  - repository: nightly_feedstock
    type: github
    name: cctbx/nightly-feedstock
    endpoint: cctbx

jobs:
- job: Update_nightly_feedstock
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 120

  # variables for version
  variables:
    year: $(Get-Date -Format yyyy)
    month: $(Get-Date -Format MM)
    day: $(Get-Date -Format dd)
    version: $(year).$(month)a$(day)

  steps:

  # set version
  - powershell: |
      $trimmed_month = $(month).TrimStart("0")
      $trimmed_day = $(day).TrimStart("0")
      Write-Host $trimmed_month
      Write-Host $trimmed_day
      Write-Host "##vso[task.setVariable variable=year]$(year)"
      Write-Host "##vso[task.setVariable variable=month]$trimmed_month"
      Write-Host "##vso[task.setVariable variable=day]$trimmed_day"
      Write-Host $(year)
      Write-Host $(month)
      Write-Host $(day)
    displayName: Set variables from date

  - script: |
      version=$(year).$(month)a$(day)
      echo "##vso[task.setVariable variable=version]$version"
      echo $(version)
    displayName: Set version

  - script: |
      set -x -e
      release=`echo $(Build.SourceBranch) | sed 's/refs\/heads\/releases\///'`
      echo "##vso[task.setVariable variable=version]$release"
      echo $(version)
    displayName: Override version for release branch
    condition: startswith(variables['Build.SourceBranch'], 'refs/heads/releases/')

  # download sources
  - checkout: nightly_feedstock
    persistCredentials: true

  # update cctbx/nightly-feedstock to trigger conda package builds
  - script: |
      set -x -e

      git config user.name "Billy K. Poon"
      git config user.email "bkpoon@lbl.gov"

      git checkout test

      python ./recipe/update_meta.py \
        --organization $(System.CollectionId) \
        --project $(System.TeamProject) \
        --runId $(Build.TriggeredBy.BuildId) \
        --new-version $(version) \
        --meta-path ./recipe/meta.yaml

      git commit -am "Update for v$(version)"
      git push -f -u origin test
    displayName: Update nighty-feedstock
    condition: eq(variables['Build.Reason'], 'ResourceTrigger')
