# Update GitLab copy of cctbx_project for email diffs

# no continuous integration builds or pull requests
trigger: none
pr: none

schedules:
  - cron: '*/10 * * * *'
    displayName: Check for commits
    branches:
      include:
      - master
    always: true
    batch: true

resources:
  repositories:
  - repository: cctbx_project
    type: github
    name: cctbx/cctbx_project
    endpoint: cctbx
    trigger:
      batch: true
      branches:
        include:
        - master

steps:

- task: InstallSSHKey@0
  inputs:
    knownHostsEntry: boa.lbl.gov ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAnPOtqyYASs6hc3fsmUQn92ovSozJsMsJyrMWjppUERX1tD4Fh0D7YaNhLvYpKi5mYVREo+tsKoOatCcqKGHCONWpzx7JHXUzfIBsy6nCeygRyyW4yuyoCuYFvOYLkaM4PrN/7XaZEnp1ux6/ZcbRxBDNK4f42svJUV39OX33tRuQWpP+O85paJr1ePHVz6U2n14a+3fRN3DBMti1dJuKOThU4djYEBQimx54pnW71eYORN2oUz+N/4RHAcomtxZpcUMl3Qadw8hD4s1XM6fzJ0Que7KefnnrPOgAEtZxKl9j09aaE70Oh+ie5Y6ckwddJ/4qZB5m2tBaEi3xuy0TSQ==
    sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA7XgVgdU9GmZuo5yVyW/htrAuxe7ypuq7IowWwfUC0WZw9SPzQ8kOGj63plF3ytx/qpgvUlS1AiywO20rZ83gHmRdAiuvt9laH09KlWEUhIhAQTzesqBG5aUT0MKo01yxijoRl5HC8w/MdOanc0h01e6IxnZvgG0N30RB1i4xVPCtR/VBmXSp4R0T+Q/gJjfQssuBxHVMrrute4V3uUHek58FL2QgUB0+zq6ipETjuCJxTSyYVAFtCYDPYs+0lAYYkWrXALCr9kX9s22jYtkyv5kNw6mEW8nhtA7GbTdJLv4M6/WYtcvQV8TDcNCfltOfl81U3gcZ9zhQDKGVoNaJEw== buildbot@cci.lbl.gov
    sshKeySecureFile: id_rsa
  displayName: Download SSH key

- checkout: none

- script: |
    set -xe
    cd $(Pipeline.Workspace)
    git clone git@github.com:cctbx/cctbx_project.git
    cd cctbx_project
    git checkout master
  displayName: Checkout GitHub copy

- script: |
    set -xe
    ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    cd $(Pipeline.Workspace)
    cd cctbx_project
    git remote add gitlab git@gitlab.com:cctbx/cctbx_project.git
    git fetch gitlab
    git push -u gitlab master
  displayName: Update GitLab copy
