# Nightly tests of conda-forge package

# no continuous integration builds or pull requests
trigger: none
pr: none

# schedule run for Python 3.12
schedules:
  - cron: '0 8 * * *'
    displayName: Run Python 3.12 tests
    branches:
      include:
      - py312_test

resources:
  repositories:
  - repository: cctbx_project
    type: github
    name: cctbx/cctbx_project
    endpoint: cctbx
  # trigger tests after build finishes
  pipelines:
  - pipeline: nightly_feedstock
    project: feedstock-builds
    source: nightly-feedstock
    trigger:
      branches:
        include:
        - main

jobs:
  - template: ./test-linux.yml
    parameters:
      CHANNEL: cctbx-nightly
  - template: ./test-osx.yml
    parameters:
      CHANNEL: cctbx-nightly
  - template: ./test-win.yml
    parameters:
      CHANNEL: cctbx-nightly
