steps:
  # add conda to path
  - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
    displayName: Add conda to PATH

  - script: |
      conda create -n test -c conda-forge -y cctbx-base python=$(PY_VER) junit-xml
    displayName: Construct latest conda environment

  # module=cbflib_adaptbx
  - script: |
      call activate test
      cd $(Pipeline.Workspace)
      mkdir tests
      cd tests
      call libtbx.run_tests_parallel \
        module=annlib_adaptbx \
        module=boost_adaptbx \
        module=cctbx \
        module=cctbx_website \
        module=cma_es \
        module=fable \
        module=gltbx \
        module=iotbx \
        module=libtbx \
        module=rstbx \
        module=scitbx \
        module=smtbx \
        module=spotfinder \
        nproc=4
    failOnStderr: false
    displayName: Run subset of tests

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Pipeline.Workspace)/tests/output.xml'
