# External parameters
#   CHANNEL

jobs:
  - job: win_64
    pool:
      vmImage: windows-latest
    timeoutInMinutes: 120
    strategy:
      maxParallel: 3
      matrix:
        python3.7:
          PY_VER: 3.7
        python3.8:
          PY_VER: 3.8
        python3.9:
          PY_VER: 3.9
        python3.10:
          PY_VER: 3.10
        python3.11:
          PY_VER: 3.11
        python3.12:
          PY_VER: 3.12

    steps:
      - checkout: self
        path: ./cctbx

      - checkout: cctbx_project
        path: ./cctbx_project

      # add conda to path
      - powershell: Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
        displayName: Add conda to PATH

      - script: |
          conda remove -n test -y --all
          conda create -n test -c ${{ parameters.CHANNEL }} -c conda-forge -y cctbx python=$(PY_VER) junit-xml setuptools=69.0 wheel=0.42
          call activate test
          pip install pytest==7.0
        displayName: Construct latest conda environment
        retryCountOnTaskFailure: 3

      # copy extra test files
      - script: |
          call activate test
          cd $(Pipeline.Workspace)
          xcopy /Y /E /I cctbx_project\ucif\antlr3 %CONDA_PREFIX%\lib\site-packages\ucif\antlr3
          xcopy /Y cctbx_project\ucif\*.cpp %CONDA_PREFIX%\lib\site-packages\ucif\
          xcopy /Y cctbx_project\ucif\examples\*.cpp %CONDA_PREFIX%\lib\site-packages\ucif\examples\
          xcopy /Y /E /I cctbx_project\fable\test\lenient %CONDA_PREFIX%\lib\site-packages\fable\test\lenient
          xcopy /Y /E /I cctbx_project\fable\test\semantic_error %CONDA_PREFIX%\lib\site-packages\fable\test\semantic_error
          xcopy /Y /E /I cctbx_project\fable\test\syntax_error %CONDA_PREFIX%\lib\site-packages\fable\test\syntax_error
          xcopy /Y /E /I cctbx_project\fable\test\unsupported %CONDA_PREFIX%\lib\site-packages\fable\test\unsupported
          xcopy /Y /E /I cctbx_project\fable\test\valid %CONDA_PREFIX%\lib\site-packages\fable\test\valid

          xcopy /Y cctbx_project\rstbx\indexing\tst_auto_monoscan.py %CONDA_PREFIX%\lib\site-packages\rstbx\indexing\tst_auto_monoscan.py
          xcopy /Y cctbx_project\rstbx\indexing\tst_dataset1.py %CONDA_PREFIX%\lib\site-packages\rstbx\indexing\tst_dataset1.py
        displayName: Copy additional test files for fable and iotbx tests

      - script: |
          call activate test
          cd $(Pipeline.Workspace)
          del phenix_regression.zip
          python cctbx\.azure-pipelines\scripts\download-phenix-regression.py --organization cctbx --project cctbx_project
          unzip phenix_regression.zip
          mv phenix_regression %CONDA_PREFIX%\lib\site-packages
        displayName: Copy phenix_regression artifact
        retryCountOnTaskFailure: 3

      # module=cbflib_adaptbx
      - script: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          call activate test
          cd $(Pipeline.Workspace)
          rmdir /S /Q tests
          mkdir tests
          cd tests
          call libtbx.run_tests_parallel ^
            module=annlib_adaptbx ^
            module=boost_adaptbx ^
            module=cctbx ^
            module=cctbx_website ^
            module=cma_es ^
            module=fable ^
            module=gltbx ^
            module=iotbx ^
            module=libtbx ^
            module=rstbx ^
            module=scitbx ^
            module=smtbx ^
            module=spotfinder ^
            nproc=4
        failOnStderr: false
        displayName: Run subset of tests
        retryCountOnTaskFailure: 3

      - task: PublishTestResults@2
        condition: succeededOrFailed()
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(Pipeline.Workspace)/tests/output.xml'
