jobs:
  - job: linux_64
    pool:
      vmImage: ubuntu-latest
    timeoutInMinutes: 120
    strategy:
      maxParallel: 3
      matrix:
        python3.7:
          PY_VER: 3.7
        python3.8:
          PY_VER: 3.8
        python3.9:
          PY_VER: 3.9
        python3.10:
          PY_VER: 3.10
        python3.11:
          PY_VER: 3.11

    steps:
    - template: ./templates/test-unix.yml
      parameters:
        CHANNEL: ${{ parameters.CHANNEL }}
        PY_VER: $(PY_VER)
